# Site settings
title: "The Loan Phone"
description: "Compare Car Loans, Personal Loans, Home Loans, Investment Loans, or Business Loans with zero impact on your credit score. Best personalised rates from 100+ lenders."
baseurl: "/loan-phone-website"
url: "https://amsumo9.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Collections for future content organization
collections:
  services:
    output: true
    permalink: /:name/
  locations:
    output: true
    permalink: /locations/:name/
  posts:
    permalink: /blog/:year/:month/:day/:title/

# Default settings for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "locations"
    values:
      layout: "location"

# SEO and social media defaults
author: "The Loan Phone Team"
twitter:
  username: loanphone
facebook:
  app_id: 
  publisher: 
social:
  name: The Loan Phone
  links:
    - https://twitter.com/loanphone
    - https://facebook.com/loanphone

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
