# Site settings
title: "The Loan Phone"
description: "Compare Car Loans, Personal Loans, Home Loans, Investment Loans, or Business Loans with zero impact on your credit score. Best personalised rates from 100+ lenders."
baseurl: "/loan-phone-website"
url: "https://amsumo9.github.io"

# Contact information
contact:
  email: "loans@loanphone.com.au"
  phone: "+61440135626"
  phone_display: "0440 135 626"

# Company information
company:
  name: "The Loan Phone"
  tagline: "Your trusted partner in finding the perfect loan"
  legal_notice: "It is important for you to know that any information provided to you by Loan Phone (loanphone.com.au) is not Financial or Credit Advice"

# Feature flags
features:
  loan_widget_live: false  # Set to true when ready to go live
  partner_id: "a996e580-c961-4586-a00c-9c86968f172d"
  source_url: "https://www.loanphone.com.au"
  widget_js: "https://loanoptions-widget.s3.ap-southeast-2.amazonaws.com/v2/main/js/main.js"
  widget_css: "https://loanoptions-widget.s3.ap-southeast-2.amazonaws.com/v2/main/css/main.css"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Collections for future content organization
collections:
  services:
    output: true
    permalink: /:name/
  locations:
    output: true
    permalink: /locations/:name/
  posts:
    permalink: /blog/:year/:month/:day/:title/

# Default settings for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "The Loan Phone Team"
      og_type: "website"
      og_image: "/assets/images/og-default.jpg"
      twitter_image: "/assets/images/twitter-default.jpg"
      meta_author: "The Loan Phone Team"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "The Loan Phone Team"
      og_type: "article"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
      author: "The Loan Phone Team"
      og_type: "website"
      category: "loan-services"
  - scope:
      path: ""
      type: "locations"
    values:
      layout: "location"
      author: "The Loan Phone Team"
      og_type: "website"
      category: "locations"

# Site-wide SEO defaults
seo:
  default_title: "The Loan Phone - Compare Loans Fast"
  default_description: "Compare Car Loans, Personal Loans, Home Loans, Investment Loans, or Business Loans with zero impact on your credit score."
  default_keywords: "loans, car loans, home loans, personal loans, business loans, australia"
  fallback_image: "/assets/images/og-default.jpg"

# Content validation rules (for future reference)
validation:
  required_fields:
    pages: ["title", "meta_description"]
    posts: ["title", "meta_description", "date"]
    services: ["title", "meta_description", "service_type"]
  max_lengths:
    title: 60
    meta_description: 160
    excerpt: 300

# SEO and social media defaults
author: "The Loan Phone Team"
twitter:
  username: loanphone
facebook:
  app_id: 
  publisher: 
social:
  name: The Loan Phone
  links:
    - https://twitter.com/loanphone
    - https://facebook.com/loanphone

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
