# Site settings
title: "The Loan Phone"
description: "Compare Car Loans, Personal Loans, Home Loans, Investment Loans, or Business Loans with zero impact on your credit score. Australia's trusted loan comparison service."
baseurl: "/loan-phone-website"
url: "https://amsumo9.github.io"

# Contact information
contact:
  email: "loans@loanphone.com.au"
  phone: "+61440135626"
  phone_display: "0440 135 626"

# Company information
company:
  name: "The Loan Phone"
  tagline: "Your trusted partner in finding the perfect loan"
  legal_notice: "It is important for you to know that any information provided to you by Loan Phone (loanphone.com.au) is not Financial or Credit Advice. You must read the Privacy Policy."

# Feature flags
features:
  loan_widget_live: true # Set to true when ready to go live (false when testing)
  partner_id: "a996e580-c961-4586-a00c-9c86968f172d"
  source_url: "https://www.loanphone.com.au"
  widget_js: "https://loanoptions-widget.s3.ap-southeast-2.amazonaws.com/v2/main/js/main.js"
  widget_css: "https://loanoptions-widget.s3.ap-southeast-2.amazonaws.com/v2/main/css/main.css"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Blog settings
paginate: 6
paginate_path: "/blog/page:num/"

# Collections
collections:
  services:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Default settings for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "The Loan Phone Team"
      og_type: "website"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "services"
      author: "The Loan Phone Team"
      og_type: "website"
      category: "loan-services"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "The Loan Phone Team"
      og_type: "article"
      category: "Financial Tips"

# SEO defaults
seo:
  default_title: "The Loan Phone - Compare Loans Fast"
  default_description: "Compare Car Loans, Personal Loans, Home Loans, Investment Loans, or Business Loans with zero impact on your credit score. Get pre-approved in minutes."
  default_keywords: "loans, car loans, home loans, personal loans, business loans, australia, loan comparison, finance"
  fallback_image: "/assets/images/og-default.jpg"

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md

# Include files
include:
  - _pages

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Site navigation (optional - for future use)
navigation:
  main:
    - name: "How It Works"
      url: "/#how-it-works"
    - name: "Services" 
      url: "/services/"
    - name: "Locations"        
      url: "/locations/"       
      type: "page"            
    - name: "Blog"
      url: "/blog/"
    - name: "About Us"
      url: "/about/"
